---
- name: ensure drupal7 packages are the latest
  apt: name={{ item }} state=latest
  sudo: yes
  with_items:
    - curl
    - unzip
    - drush

- name: ensure drupal settings is the present when database is provisioned
  template: >
    src=settings.php
    dest=/var/www/sites/default/settings.php
    force=no
  when: hostvars.db.dbdata
