---
- hosts: all
  sudo: yes
  tasks:
    - name: ensure apt cache is the latest
      apt: update_cache=yes upgrade=yes cache_valid_time=86400

- hosts: web
  sudo: yes
  tasks:
    - name: ensure web packages are the latest
      apt: name={{ item }} state=latest
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5
        - php-pear
        - php5-gd
        - php5-curl
        - php5-sqlite
        - php5-mysql
        - php5-pgsql
        - curl
        - unzip
        - drush

    - name: ensure apache modules are enabled
      apache2_module: name={{ item }}
      with_items:
        - rewrite
        - expires
        - auth_basic
        - headers
      register: a2module

    - name: ensure apache site is configured
      copy: >
        src=site.conf
        dest=/etc/apache2/sites-available/default
      register: siteconf

    - name: ensure php is configured
      lineinfile: >
        dest=/etc/php5/apache2/php.ini
        regexp="max_execution_time = .*"
        line="max_execution_time = 120"
      register: phpconf

    - name: ensure apache is restarted when needed
      service: name=apache2 state=restarted
      when: a2module.changed or siteconf.changed or phpconf.changed

- hosts: db
  sudo: yes
  tasks:
    - name: ensure db packages are the latest
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        # for ansible
        - python-mysqldb

    - name: ensure mysql is listening to all
      lineinfile: >
        dest=/etc/mysql/my.cnf
        regexp=^bind-address
        line="bind-address = *"
        backrefs=yes
      register: mysqlconf

    - name: ensure mysql is restarted when needed
      service: name=mysql state=restarted
      when: mysqlconf.changed

    - name: ensure drupal database user is present
      mysql_user: >
        name=drupal
        password=foobar
        host=%
        login_user=root
        login_password=""
        priv="drupal.*:ALL"

    - name: ensure drupal database is present
      mysql_db: >
        name=drupal
        login_user=root
        login_password=""

    - name: copy database dump file to db server when it exists
      ignore_errors: yes
      copy: src=database.mysql.gz dest=/tmp
      register: dbfile

    - name: ensure database is provisioned when needed
      mysql_db: >
        name=drupal
        login_user=root
        login_password=""
        target=/tmp/database.mysql.gz
        state=import
      when: dbfile and dbfile.changed
      register: dbdata

- hosts: web
  tasks:
    - name: ensure drupal settings is the present when database is provisioned
      copy: >
        src=settings.php
        dest=/var/www/sites/default/settings.php
      when: hostvars.db.dbdata.changed
